apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multipod
  name: multipod
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do echo ‘Hi I am from Main container’ >> /var/log/index.html; sleep 5; done
    image: busybox
    name: multipod
    resources: {}
    volumeMounts:
    - name: vol
      mountPath: /var/log
  - image: nginx
    name: pod2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: vol
      mountPath: /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  volumes:
  - name: vol
    emptyDir: {}
  restartPolicy: Never
status: {}

