apiVersion: v1
kind: Pod
metadata:
  name: multicontainerpod
  labels:
    run: multicontainer
spec:
  containers:
  - name: container1
    image: busybox
  - name: container2
    image: nginx
  restartPolicy: Never