apiVersion: v1
kind: Pod
metadata:
  name: pod-with-persistent-volume-claim
  labels:
    app: withvolume
spec:
  containers:
  - name: container1
    image: nginx
    # start - This section mount the volume to container 
    volumeMounts:
      - name: volclaim # This name should match the name from volume
        mountPath: /mnt/vol
    # end
  restartPolicy: Never
  # start - This section mount the volume to pod 
  volumes:
    - name: volclaim # Give the name of volume
      persistentVolumeClaim: # This tells that the volume is getting attached to a pod which is comnig from claim
        claimName: volume-claim # Note: This claim  should be pre-created
  # end