apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
  - name: container1
    image: busybox
    resources:
        requests: # if limit is not specified,  it will be unlimited by default
          cpu: ".2"
          memory: "50Mi"
  restartPolicy: Never