apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: env-var-pod
  name: env-pod-env
spec:
  containers:
  - image: nginx
    name: env-var-pod
    resources: {}
    #envFrom:
    #- configMapRef:
    #   name: keyvalcfgmap
    env:
    - name: NEW
      valueFrom:
       configMapKeyRef:
        key: key1
        name: envmap
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
