apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: secretvolume
      mountPath: /mnt/secret
  dnsPolicy: ClusterFirst
  volumes:
  - name: secretvolume
    secret:
     secretName: my-secret
  restartPolicy: Never
status: {}
