apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
  - name: container1 # container name
    image: busybox
    resources:
        requests: # if limit is not specified,  it will be unlimited by default
          cpu: ".2"
          memory: "50Mi"
        limits: # if you only specify limit, then request will be automatically  assigned same as limit.
          cpu: ".4"
          memory: "100Mi"
  restartPolicy: Never