apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx1
    volumeMounts:
    - name: vol1
      mountPath: /data1
    command: ["/bin/sh", "-c", "touch /data1/abc.txt; sleep 4800"]
  - image: nginx
    name: nginx2
    volumeMounts:
    - name: vol1
      mountPath: /data2
    command: ["/bin/sh", "-c", "cp /data2/abc.txt /; sleep 4800"]
  volumes:
  - name: vol1
    emptyDir: {}
