apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis
spec:
  containers:
  - image: redis
    name: redis
    resources: {}
    volumeMounts:
    - name: vol1
      mountPath: /var/disk
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: vol1
    emptyDir: {}
status: {}
