apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
  - name: container1
    image: busybox
    resources:
      limits: # if you only specify limit, then request will be automatically  assigned same as limit.
        cpu: ".4"
        memory: "100Mi"
  restartPolicy: Never