apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busyboxpod
  name: busyboxpod
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busyboxpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
