apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-svc
  name: nginx-svc
  namespace: demospace
spec:
  ports:
  - name: nginx-svc
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-deploy
  type: ClusterIP
status:
  loadBalancer: {}
