apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: demo-job
  namespace: demospace
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        name: demo-job
        resources: {}
      restartPolicy: Never
status: {}