apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: addnumber
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        name: addnumber
        resources: {}
      restartPolicy: Never
status: {}