apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: counter
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: counter
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: busybox
            name: counter
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
