apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hello-world.ingress
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: web1
          servicePort: 80
      - path: /v2
        pathType: Prefix
        backend:
         serviceName: web2
         servicePort: 8080
