apiVersion: v1
kind: Secret
metadata:
    name: mongosecret
type: Opaque
data:
    mongo-db-username: bW9uZ28= # base64 encoded string for mongo
    mongo-db-password: bW9uZ29wd2Q= # base64  encoded string for mongopwd
